// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconAmon } from "../../../icons/mono/build/icon-amon.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const AmonIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconAmon.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  AmonIcon.displayName = 'AmonIcon';
}

export default AmonIcon;