// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconMonad } from "../../../icons/mono/build/icon-monad.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const MonadIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconMonad.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  MonadIcon.displayName = 'MonadIcon';
}

export default MonadIcon;