// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconStatamon } from "../../../icons/mono/build/icon-statamon.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const StatamonIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconStatamon.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  StatamonIcon.displayName = 'StatamonIcon';
}

export default StatamonIcon;