// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconArc } from "../../../icons/full/build/icon-arc.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const ArcIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconArc.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  ArcIcon.displayName = 'ArcIcon';
}

export default ArcIcon;