// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconMon } from "../../../icons/full/build/icon-mon.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const MonIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconMon.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  MonIcon.displayName = 'MonIcon';
}

export default MonIcon;